/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppFooter: typeof import('./components/AppFooter.vue')['default']
    ConfirmDialog: typeof import('./components/use-dialog/confirm/ConfirmDialog.vue')['default']
    DialogProvider: typeof import('./components/use-dialog/DialogProvider.vue')['default']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    NavigationBar: typeof import('./components/navigation/NavigationBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SnackbarProvider: typeof import('./components/use-snackbar/SnackbarProvider.vue')['default']
    TextLabel: typeof import('./components/text-label/TextLabel.vue')['default']
    TextToActionSettingsForm: typeof import('./components/text-to-action/TextToActionSettingsForm.vue')['default']
  }
}
