/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/chat/': RouteRecordInfo<'/chat/', '/chat', Record<never, never>, Record<never, never>>,
    '/logs/': RouteRecordInfo<'/logs/', '/logs', Record<never, never>, Record<never, never>>,
    '/not-found/': RouteRecordInfo<'/not-found/', '/not-found', Record<never, never>, Record<never, never>>,
    '/settings/tta/': RouteRecordInfo<'/settings/tta/', '/settings/tta', Record<never, never>, Record<never, never>>,
    '/settings/tta/tabs/Actions': RouteRecordInfo<'/settings/tta/tabs/Actions', '/settings/tta/tabs/Actions', Record<never, never>, Record<never, never>>,
    '/settings/tta/tabs/CachedModels': RouteRecordInfo<'/settings/tta/tabs/CachedModels', '/settings/tta/tabs/CachedModels', Record<never, never>, Record<never, never>>,
    '/settings/tta/tabs/General': RouteRecordInfo<'/settings/tta/tabs/General', '/settings/tta/tabs/General', Record<never, never>, Record<never, never>>,
    '/settings/tta/tabs/SystemPrompt': RouteRecordInfo<'/settings/tta/tabs/SystemPrompt', '/settings/tta/tabs/SystemPrompt', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/chat/index.vue': {
      routes: '/chat/'
      views: never
    }
    'src/pages/logs/index.vue': {
      routes: '/logs/'
      views: never
    }
    'src/pages/not-found/index.vue': {
      routes: '/not-found/'
      views: never
    }
    'src/pages/settings/tta/index.vue': {
      routes: '/settings/tta/'
      views: never
    }
    'src/pages/settings/tta/tabs/Actions.vue': {
      routes: '/settings/tta/tabs/Actions'
      views: never
    }
    'src/pages/settings/tta/tabs/CachedModels.vue': {
      routes: '/settings/tta/tabs/CachedModels'
      views: never
    }
    'src/pages/settings/tta/tabs/General.vue': {
      routes: '/settings/tta/tabs/General'
      views: never
    }
    'src/pages/settings/tta/tabs/SystemPrompt.vue': {
      routes: '/settings/tta/tabs/SystemPrompt'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
